//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CERA.Azure.CloudService {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class AzureAuth : global::System.Configuration.ApplicationSettingsBase {
        
        private static AzureAuth defaultInstance = ((AzureAuth)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new AzureAuth())));
        
        public static AzureAuth Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("218411ec-50a7-4c7e-b671-e3434f3775d3")]
        public string ClientId {
            get {
                return ((string)(this["ClientId"]));
            }
            set {
                this["ClientId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("73d3d213-f87a-4465-9a7e-67bd625fdf9c")]
        public string tenantId {
            get {
                return ((string)(this["tenantId"]));
            }
            set {
                this["tenantId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("HX.pn3IxFE.vH1b~xY8u3Sw078LywJO_iU")]
        public string Clientsecert {
            get {
                return ((string)(this["Clientsecert"]));
            }
            set {
                this["Clientsecert"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://login.microsoftonline.com/{0}/v2.0")]
        public string authority {
            get {
                return ((string)(this["authority"]));
            }
            set {
                this["authority"] = value;
            }
        }
    }
}
